package com.codeup.actions

import com.codeup.analyzer.AnthropicClient
import com.codeup.catalogue.CatalogueLoader
import com.codeup.intent.IntentConfig
import com.codeup.intent.LayerRule
import com.codeup.knowledge.KnowledgeStore
import com.codeup.scanner.GraphBuilder
import com.codeup.scanner.scanWorkspace
import com.codeup.security.ApiKeyManager
import com.codeup.settings.CodeupSettings
import com.intellij.openapi.actionSystem.*
import com.intellij.openapi.fileEditor.OpenFileDescriptor
import com.intellij.openapi.progress.*
import com.intellij.openapi.ui.Messages
import com.intellij.openapi.vfs.LocalFileSystem
import kotlinx.coroutines.runBlocking
import org.yaml.snakeyaml.DumperOptions
import org.yaml.snakeyaml.Yaml
import java.io.File

class SuggestIntentAction : AnAction("Suggest Architectural Intent") {
    override fun actionPerformed(e: AnActionEvent) {
        val project = e.project ?: return
        val rootPath = project.basePath ?: return
        val rootDir = File(rootPath)
        val apiKey = ApiKeyManager.getApiKey() ?: run {
            Messages.showErrorDialog(project, "Set an Anthropic API key first.", "Codeup")
            return
        }

        ProgressManager.getInstance().run(object : Task.Backgroundable(project, "Codeup: drafting intent.yaml", true) {
            override fun run(indicator: ProgressIndicator) {
                indicator.text = "Scanning project structure..."
                val index = scanWorkspace(rootDir, indicator)
                if (indicator.isCanceled) return
                val graph = GraphBuilder.buildGraph(index)
                val knowledge = KnowledgeStore.getInstance(project)
                val catalogue = CatalogueLoader.loadCatalogue(knowledge.patterns.toList())
                val client = AnthropicClient({ apiKey }, CodeupSettings.getInstance().state.model)

                val dirSummary = buildDirSummary(index)
                val prompt = "You are analyzing a software project. Based on the directory structure below, suggest architectural layers as a YAML list. Each entry: `layer: name`, `match: glob`, `cannotDependOn: [layer names]`. Keep it to 3-6 layers.\n\n$dirSummary"

                indicator.text = "Asking Claude for layer suggestions..."
                // Simple extraction: ask model for YAML in response
                val response = runBlocking {
                    client.analyze(com.codeup.analyzer.LLMAnalyzeRequest(
                        systemPrompt = "Respond with a YAML block only. No prose. Format: layers:\\n  - layer: ...\\n    match: ...\\n    cannotDependOn: [...]",
                        userPrompt = prompt,
                        tool = com.codeup.analyzer.REPORT_FINDING_TOOL,
                        maxOutputTokens = 1024,
                        cancellationCheck = { indicator.isCanceled },
                    ))
                }

                // Build a default intent suggestion based on directory structure
                val intentYaml = buildDefaultIntent(index)
                val targetFile = File(rootDir, ".codeup/intent.yaml")
                com.intellij.openapi.application.ApplicationManager.getApplication().invokeLater {
                    if (targetFile.exists()) {
                        val choice = Messages.showYesNoDialog(project, ".codeup/intent.yaml already exists. Overwrite?", "Codeup", Messages.getWarningIcon())
                        if (choice != Messages.YES) return@invokeLater
                    }
                    targetFile.parentFile.mkdirs()
                    targetFile.writeText(intentYaml)
                    val vf = LocalFileSystem.getInstance().refreshAndFindFileByIoFile(targetFile)
                    if (vf != null) OpenFileDescriptor(project, vf).navigate(true)
                    Messages.showInfoMessage(project, "Wrote .codeup/intent.yaml. Review and adjust the layer rules.", "Codeup")
                }
            }
        })
    }

    private fun buildDirSummary(index: com.codeup.model.ProjectIndex): String {
        val dirs = index.files.map { it.path.substringBeforeLast("/", "") }.filter { it.isNotEmpty() }.toSet().sorted().take(50)
        return "Directories:\n" + dirs.joinToString("\n") { "  $it/" }
    }

    private fun buildDefaultIntent(index: com.codeup.model.ProjectIndex): String {
        val opts = DumperOptions().also { it.defaultFlowStyle = DumperOptions.FlowStyle.BLOCK; it.width = 100 }
        val topDirs = index.files.map { it.path.split("/").firstOrNull() ?: "" }
            .filter { it.isNotEmpty() }.groupBy { it }.entries.sortedByDescending { it.value.size }.take(5).map { it.key }
        val layers = topDirs.map { dir ->
            mapOf("layer" to dir, "match" to "$dir/**", "cannotDependOn" to emptyList<String>())
        }
        return "# Generated by Codeup — review and adjust before committing\n" + Yaml(opts).dump(mapOf("layers" to layers))
    }

    override fun update(e: AnActionEvent) { e.presentation.isEnabled = e.project != null }
    override fun getActionUpdateThread() = ActionUpdateThread.BGT
}